#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "Push direto na branch '$branch' está bloqueado."
  echo "Use um Pull Request para fazer merge nessa branch."
  exit 1
fi

exit 0