sonar.projectKey=oficina-os-service
sonar.projectName=oficina-os-service
sonar.organization=postech

sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.language=kotlin

sonar.kotlin.coverage.reportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=\
  **/OficinaOsServiceApplication.kt,\
  **/infra/repository/**,\
  **/infra/nosql/**,\
  **/domain/enum/**,\
  **/domain/model/**,\
  **/infra/dto/**

sonar.coverage.exclusions=\
  **/OficinaOsServiceApplication.kt,\
  **/infra/repository/**,\
  **/infra/nosql/**,\
  **/domain/enum/**,\
  **/domain/model/**,\
  **/infra/dto/**
