services:
  # Banco Relacional exclusivo para o Microsserviço de OS
  db-os:
    image: postgres:16-alpine
    container_name: oficina-os-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: oficina_os_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345os
    volumes:
      - os_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d oficina_os_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb-os:
    # Banco Não-Relacional para o Histórico/Timeline da OS
    image: mongo:6.0
    container_name: oficina-os-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: os_history
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345mongo
    volumes:
      - os_mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: oficina-os-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - os_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 10

  os-service:
    build: .
    container_name: oficina-os-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db-os
      DB_NAME: oficina_os_db
      DB_USER: postgres
      DB_PASSWORD: 12345os
      MONGO_URI: ${MONGO_URI:-mongodb://admin:12345mongo@mongodb-os:27017/os_history?authSource=admin}
      RABBIT_HOST: ${RABBIT_HOST:-rabbitmq}
      RABBIT_PORT: ${RABBIT_PORT:-5672}
      RABBIT_USER: ${RABBIT_USER:-guest}
      RABBIT_PASS: ${RABBIT_PASS:-guest}
      RABBIT_VHOST: ${RABBIT_VHOST:-/}
      RABBIT_SSL_ENABLED: ${RABBIT_SSL_ENABLED:-false}
      BILLING_SERVICE_URL: http://billing-service
      EXECUTION_SERVICE_URL: http://execution-service
    depends_on:
      db-os:
        condition: service_healthy
      mongodb-os:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  os_postgres_data:
  os_mongo_data:
  os_rabbitmq_data:
