apiVersion: v1
kind: ConfigMap

metadata:
  name: os-service-config
  namespace: oficina-mvp-develop

data:
  SPRING_PROFILES_ACTIVE: "docker"
  DD_ENV: "develop"

  # PostgreSQL
  DB_HOST: "app-postgres-db-app-cluster-develop.rds.amazonaws.com"
  DB_NAME: "oficina_os_db"
  DB_USER: "postgres"

  # MongoDB Atlas
  MONGO_DATABASE: "os_history"

  # RabbitMQ CloudAMQP (host, usuário, senha e vhost vêm do Secret)
  RABBIT_PORT: "5671"
  RABBIT_SSL_ENABLED: "true"

  # URLs dos outros microsserviços
  BILLING_SERVICE_URL: "http://billing-service.oficina-mvp-develop.svc.cluster.local"
  EXECUTION_SERVICE_URL: "http://execution-service.oficina-mvp-develop.svc.cluster.local"
